# @format

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::605185620680:user/paul
      username: paul
      groups:
        - system:masters
